version: 2
jobs:
  build:
    working_directory: ~/AndroidSDKTests
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Create Build
          command: ./gradlew clean assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew :AndroidSDKTests:testDebugUnitTest --no-daemon --max-workers 2
 
