version: 2
jobs:
  build:
    working_directory: ~/AndroidSDKTests
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx1024m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2

    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Create Build
          command: ./gradlew clean assembleDebug --no-daemon --max-workers 2
      - run:
          name: Run Tests
          command: ./gradlew :AndroidSDKTests:testDebugUnitTest --no-daemon -Pkotlin.incremental=false --max-workers=2 # --info --stacktrace

 
